id: P008201
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:07:41.229696
source_metadata:
  id: bdr:W2PD19122
  title: དཀར་མཛེས་ཁུལ་རིག་གནས་ལོ་རྒྱུས་ཀྱི་དཔྱད་གཞིའི་ཡིག་རིགས།༼༣༽
  author: ''
  volumes:
    3b5e23650a1845c5b608721b60dc94fc:
      image_group_id: I4PD4366
      title: ''
      volume_number: 1
      total_pages: 330
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
