id: I27D9E961
legacy_id: P008201
ocr_import_info:
  bdrc_scan_id: W2PD19122
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T17:34:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T10:28:42.072434+00:00'
last_modified: 2022-09-03 18:28:55.145937
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD19122
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2PD19122
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཀར་མཛེས་ཁུལ་རིག་གནས་ལོ་རྒྱུས་ཀྱི་དཔྱད་གཞིའི་ཡིག་རིགས།༼༣༽
statistics:
  ocr_word_mean_confidence_index: 0.6123488398830593
  ocr_word_median_confidence_index: 0.6800000071525574
quality: null
bases:
  I4PD4366:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4PD4366
      total_pages: 330
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4PD4366.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6123488398830593
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
